name: lifelog
description: hsu
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  retrofit: ^4.4.1
  dio: ^5.7.0
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.4
  pretty_dio_logger: ^1.4.0
  table_calendar: ^3.1.2
  fl_chart: ^0.65.0
  logger: ^2.4.0
  mockito: ^5.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  retrofit_generator: ^8.2.1

flutter:
  uses-material-design: true
